/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LearningActivity service. Represents a row in the &quot;Lms_LearningActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lms.model.impl.LearningActivityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lms.model.impl.LearningActivityImpl}.
 * </p>
 *
 * @author cvicente
 * @see LearningActivity
 * @see com.liferay.lms.model.impl.LearningActivityImpl
 * @see com.liferay.lms.model.impl.LearningActivityModelImpl
 * @generated
 */
public interface LearningActivityModel extends BaseModel<LearningActivity>,
	GroupedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a learning activity model instance should use the {@link LearningActivity} interface instead.
	 */

	/**
	 * Returns the primary key of this learning activity.
	 *
	 * @return the primary key of this learning activity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this learning activity.
	 *
	 * @param primaryKey the primary key of this learning activity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this learning activity.
	 *
	 * @return the uuid of this learning activity
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this learning activity.
	 *
	 * @param uuid the uuid of this learning activity
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the act ID of this learning activity.
	 *
	 * @return the act ID of this learning activity
	 */
	public long getActId();

	/**
	 * Sets the act ID of this learning activity.
	 *
	 * @param actId the act ID of this learning activity
	 */
	public void setActId(long actId);

	/**
	 * Returns the company ID of this learning activity.
	 *
	 * @return the company ID of this learning activity
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this learning activity.
	 *
	 * @param companyId the company ID of this learning activity
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this learning activity.
	 *
	 * @return the user ID of this learning activity
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this learning activity.
	 *
	 * @param userId the user ID of this learning activity
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this learning activity.
	 *
	 * @return the user uuid of this learning activity
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this learning activity.
	 *
	 * @param userUuid the user uuid of this learning activity
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this learning activity.
	 *
	 * @return the group ID of this learning activity
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this learning activity.
	 *
	 * @param groupId the group ID of this learning activity
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user name of this learning activity.
	 *
	 * @return the user name of this learning activity
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this learning activity.
	 *
	 * @param userName the user name of this learning activity
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this learning activity.
	 *
	 * @return the create date of this learning activity
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this learning activity.
	 *
	 * @param createDate the create date of this learning activity
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this learning activity.
	 *
	 * @return the modified date of this learning activity
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this learning activity.
	 *
	 * @param modifiedDate the modified date of this learning activity
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this learning activity.
	 *
	 * @return the status of this learning activity
	 */
	public int getStatus();

	/**
	 * Sets the status of this learning activity.
	 *
	 * @param status the status of this learning activity
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this learning activity.
	 *
	 * @return the status by user ID of this learning activity
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this learning activity.
	 *
	 * @param statusByUserId the status by user ID of this learning activity
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this learning activity.
	 *
	 * @return the status by user uuid of this learning activity
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this learning activity.
	 *
	 * @param statusByUserUuid the status by user uuid of this learning activity
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this learning activity.
	 *
	 * @return the status by user name of this learning activity
	 */
	@AutoEscape
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this learning activity.
	 *
	 * @param statusByUserName the status by user name of this learning activity
	 */
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this learning activity.
	 *
	 * @return the status date of this learning activity
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this learning activity.
	 *
	 * @param statusDate the status date of this learning activity
	 */
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the title of this learning activity.
	 *
	 * @return the title of this learning activity
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this learning activity.
	 *
	 * @param title the title of this learning activity
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this learning activity.
	 *
	 * @return the description of this learning activity
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this learning activity.
	 *
	 * @param description the description of this learning activity
	 */
	public void setDescription(String description);

	/**
	 * Returns the type ID of this learning activity.
	 *
	 * @return the type ID of this learning activity
	 */
	public int getTypeId();

	/**
	 * Sets the type ID of this learning activity.
	 *
	 * @param typeId the type ID of this learning activity
	 */
	public void setTypeId(int typeId);

	/**
	 * Returns the startdate of this learning activity.
	 *
	 * @return the startdate of this learning activity
	 */
	public Date getStartdate();

	/**
	 * Sets the startdate of this learning activity.
	 *
	 * @param startdate the startdate of this learning activity
	 */
	public void setStartdate(Date startdate);

	/**
	 * Returns the enddate of this learning activity.
	 *
	 * @return the enddate of this learning activity
	 */
	public Date getEnddate();

	/**
	 * Sets the enddate of this learning activity.
	 *
	 * @param enddate the enddate of this learning activity
	 */
	public void setEnddate(Date enddate);

	/**
	 * Returns the precedence of this learning activity.
	 *
	 * @return the precedence of this learning activity
	 */
	public int getPrecedence();

	/**
	 * Sets the precedence of this learning activity.
	 *
	 * @param precedence the precedence of this learning activity
	 */
	public void setPrecedence(int precedence);

	/**
	 * Returns the tries of this learning activity.
	 *
	 * @return the tries of this learning activity
	 */
	public long getTries();

	/**
	 * Sets the tries of this learning activity.
	 *
	 * @param tries the tries of this learning activity
	 */
	public void setTries(long tries);

	/**
	 * @deprecated Renamed to {@link #isApproved()}
	 */
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this learning activity is approved.
	 *
	 * @return <code>true</code> if this learning activity is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this learning activity is a draft.
	 *
	 * @return <code>true</code> if this learning activity is a draft; <code>false</code> otherwise
	 */
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this learning activity is expired.
	 *
	 * @return <code>true</code> if this learning activity is expired; <code>false</code> otherwise
	 */
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this learning activity is pending.
	 *
	 * @return <code>true</code> if this learning activity is pending; <code>false</code> otherwise
	 */
	public boolean isPending();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LearningActivity learningActivity);

	public int hashCode();

	public CacheModel<LearningActivity> toCacheModel();

	public LearningActivity toEscapedModel();

	public String toString();

	public String toXmlString();
}