/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LearningType service. Represents a row in the &quot;Lms_LearningType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lms.model.impl.LearningTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lms.model.impl.LearningTypeImpl}.
 * </p>
 *
 * @author cvicente
 * @see LearningType
 * @see com.liferay.lms.model.impl.LearningTypeImpl
 * @see com.liferay.lms.model.impl.LearningTypeModelImpl
 * @generated
 */
public interface LearningTypeModel extends BaseModel<LearningType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a learning type model instance should use the {@link LearningType} interface instead.
	 */

	/**
	 * Returns the primary key of this learning type.
	 *
	 * @return the primary key of this learning type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this learning type.
	 *
	 * @param primaryKey the primary key of this learning type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this learning type.
	 *
	 * @return the uuid of this learning type
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this learning type.
	 *
	 * @param uuid the uuid of this learning type
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the type ID of this learning type.
	 *
	 * @return the type ID of this learning type
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this learning type.
	 *
	 * @param typeId the type ID of this learning type
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the name of this learning type.
	 *
	 * @return the name of this learning type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this learning type.
	 *
	 * @param name the name of this learning type
	 */
	public void setName(String name);

	/**
	 * Returns the class name of this learning type.
	 *
	 * @return the class name of this learning type
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this learning type.
	 *
	 * @param className the class name of this learning type
	 */
	public void setClassName(String className);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LearningType learningType);

	public int hashCode();

	public CacheModel<LearningType> toCacheModel();

	public LearningType toEscapedModel();

	public String toString();

	public String toXmlString();
}